services:
  - type: worker
    name: scheduler-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python combined_bot.py
    envVars:
      - key: SEND_BOT_TOKEN
        value: "8897800070:AAHcG2eHlPsE0KpZAGjcFTe7ndn8gjpQi-A"
      - key: SEND_HOUR
        value: "17"
      - key: SEND_MINUTE
        value: "30"
      - key: PYTHON_VERSION
        value: "3.12.0"

